### ISSUE TITLE
Add Action for Pylint

### ISSUE THREAD

**Issue by linuswagner** [atlarge-research/continuum#5]
[Pylint](https://github.com/PyCQA/pylint) checks code statically to find errors or enforce a coding standard.  
I think to keep code quality high (or improve it), it's a good idea to have it running in the project.  
With every commit, it checks the quality of the code base and provides a report.

**Comment by matthijssjansen** [comment]
We may want to do a 2-way setup:

1. GitHub workflow that runs on every pull request; see the (incomplete) example at the bottom from Linus
2. Pre-commit hook so people can locally check the status of their code; see dev_setup.py link in the previous post. 

```
name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
```
